{
 "title": "example-pdf-generator",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "label_values(environment)" },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(kubernetes_namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Container and Pod Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Live Pods",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "up{ad_app=\"example-pdf-generator\",environment=~\"$environment\",group=\"live\",kubernetes_namespace=~\"$namespace\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap memory used",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(nodejs_heap_size_used_bytes{ad_app=\"example-pdf-generator\",environment=~\"$environment\",group=\"live\",kubernetes_namespace=\"$namespace\"}) by (kubernetes_pod_name)",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Http server metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average time taken per request",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(http_request_duration_ms_sum{ad_app=\"example-pdf-generator\",environment=~\"$environment\",group=\"live\",kubernetes_namespace=\"$namespace\",uri=~\"/api/.*\"}/http_request_duration_ms_count{ad_app=\"example-pdf-generator\",environment=~\"$environment\",group=\"live\",kubernetes_namespace=\"$namespace\",uri=~\"/api/.*\"}) by (method,uri)",
       "legendFormat": "{{method}}{{uri}}"
      }
     ]
    },
    {
     "title": "Http 2xx requests per minute",
     "type": "graph",
     "description": "The graph shows the number of request that resulted in 2xx status code.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short", "label": "No. of requests" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_ms_count{ad_app=\"example-pdf-generator\",environment=~\"$environment\",group=\"live\",kubernetes_namespace=\"default\",status=~\"2[0-9]{2}\",uri=~\"/api/.*\"}[1m]))by (method,uri)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "2xx requests[0.95 quantile]",
     "type": "graph",
     "description": "Shows the overall 0.95 quantile of Http requests with status code 2xx",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg(histogram_quantile(0.95,http_request_duration_ms_bucket{ad_app=\"example-pdf-generator\",group=\"live\",environment=~\"$environment\",kubernetes_namespace=\"$namespace\", status=~\"2[0-9]{2}\",uri=~\"/api/.*\"})) by (method)",
       "legendFormat": "{{method}} "
      }
     ]
    },
    {
     "title": "Http 4xx requests per minute",
     "type": "graph",
     "description": "The graph shows the number of request that resulted in 4xx status code.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "No. of requests" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{ad_app=\"example-pdf-generator\",environment=~\"$environment\",kubernetes_namespace=\"$namespace\",group=\"live\",status=~\"4[0-9]{2}\",uri=~\"/api/.*\"}[1m])) by (method, uri)",
       "legendFormat": "{{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Http 5xx requests per minute",
     "type": "graph",
     "description": "The graph shows the number of request that resulted in 5xx status code.",
     "gridPos": { "h": 7, "w": 11, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "short", "label": "No. of requests" }
     ],
     "targets": [
      {
       "expr": "sum(rate(http_request_duration_ms_count{ad_app=\"example-pdf-generator\",environment=~\"$environment\",group=\"live\",kubernetes_namespace=\"default\",status=~\"5[0-9]{2}\",uri=~\"/api/.*\"}[1m]))by (method,uri)",
       "legendFormat": "{{method}}{{uri}}"
      }
     ]
    }
   ]
  }
 ]
}