spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          producer-properties:
            key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            schema.registry.url: http://localhost:8081
          consumer-properties:
            key.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            schema.registry.url: http://localhost:8081
            specific.avro.reader: true
          brokers:
            - localhost:9092
      default:
        producer:
          useNativeEncoding: true
        consumer:
          useNativeEncoding: true
      bindings:
        input:
          binder: kafka
          destination: employee-details-1
          content-type: application/*+avro
          group: group-1
          concurrency: 3
        output:
          binder: kafka
          destination: employee-details-1
          content-type: application/*+avro
